# Default values for split-test-ui.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: docker-virtual.artifactory.renhsc.com/split-test
  pullPolicy: IfNotPresent
  tag: "v1"

service:
  type: ClusterIP
  port: 443
  targetport: 443

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
    cert-manager.io/common-name: internal.test-ci.nonprd.local-os
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
